### ISSUE TITLE
register package

### ISSUE THREAD

**Issue by ya0** [insightsengineering/JointSurvivalModels.jl#22]
### Feature description

PR to [registry](https://github.com/JuliaRegistries/General)

there is a ci/cd workflow [here](https://github.com/JuliaRegistries/General?tab=readme-ov-file#registering-a-package-in-general)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
@ya0 it is public now

**Comment by ya0** [comment]
new pr for registration: https://github.com/JuliaRegistries/General/pull/101247
