### ISSUE TITLE
[Feature Request]: Renaming

### ISSUE THREAD

**Issue by ya0** [insightsengineering/JointSurvivalModels.jl#45]
### Feature description

There is some confusion with the renaming. For me the project is still under the uncapiralized "jointmodels.jl" (https://github.com/insightsengineering/jointmodels.jl ) and https://github.com/insightsengineering/JointSurvivalModels.jl reroutes to https://github.com/insightsengineering/jointmodels.jl.

The docs only appear under the jointmodels.jl (https://insightsengineering.github.io/jointmodels.jl/) and not under the JointSurvivalModels.jl website (https://insightsengineering.github.io/JointSurvivalModels.jl/). i.e. the documentation link in the `Readme` is dead while in the project description it works.

@danielinteractive Can the github project itself be renamed?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by danielinteractive** [comment]
Not sure what I did before, but now after renaming (again?) it seems to be correct. I also updated the description link.

**Comment by ya0** [comment]
It seems to be working now ... not sure what happened? I am very confused, when i made this post the link above did not work.
